apiVersion: v1
kind: ServiceAccount
metadata:
  name: topology-server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topology-server
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topology-server
subjects:
  - kind: ServiceAccount
    name: topology-server
    namespace: default
roleRef:
  kind: ClusterRole
  name: topology-server
  apiGroup: rbac.authorization.k8s.io
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology-server
  template:
    metadata:
      labels:
        app: topology-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                topologyKey: kubernetes.io/hostname
              weight: 10
            - podAffinityTerm:
                topologyKey: topology.kubernetes.io/zone
              weight: 90
      serviceAccountName: topology-server
      containers:
      - name: server
        image: docker.io/imroc/topology-server:latest
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
